### ISSUE TITLE
entity.objectProperty.remove() causes subsequent seting of this property to be null

### ISSUE THREAD

**Issue by kmfdm1** [grob/ringo-sqlstore#42] opened 2018-06-08 07:44 UTC
Entity A has an object-relation to entity B.

A.b = new B();

A.b.remove();
A.b = new B();

Result:
A.b is null

The remove and subsequent set is within an sql-transaction-block.

**Comment by grob** [comment] 2018-06-09 06:31
Sorry, i couldn't reproduce this. There are a couple of things you need to keep in mind when dealing with mapped objects, most importantly make sure you're always working with the same object instances in your transaction, otherwise you would get different states.

So i suspect you are re-fetching your `A`-instance after calling `a.b.remove()` - this is the only case i can think of where `a.b` would be null:

After calling `a.b.remove()`: `a`'s state is still **clean**, since removing a mapped object has no effect on the containing object, and `a.b` still contains a reference to the removed `B` instance. Calling `a.save()` has no effect at all, but if you re-fetch `a` you'll get an object with `a.b` containing null.

Re-assigning `a.b` to a new `B` instance marks `a` as **dirty**, so you need to `save()` it to persist the changes (and the new `B` instance). But if you re-fetch `a` before saving the changes, `a.b` would still be null.

I added a [test](https://github.com/grob/ringo-sqlstore/commit/695f2c7397423d71a364ae217d147fcb43d22001) for that, i hope it makes things clearer. If not please provide a more detailed code example.

**Comment by grob** [comment] 2018-06-20 18:57
Got a chance to see the code producing the problem, reason was a problem within the application. Closing this issue.

**Closed by grob** 2018-06-20 18:57 UTC
